// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/modules/components/Layout/DefaultLayout.vue')['default'];
    MainFrame: typeof import('./src/modules/components/Element/MainFrame.vue')['default'];
    ScreenTone: typeof import('./src/modules/components/Element/ScreenTone.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
