%YAML 1.1
---
pages:
  - name: About
    path: "/"
    layout:
      name: Layout/DefaultLayout
      metadata:
        i18n:
          en: &default
            title: About
            deco: 關於我
          zh:
            title: 關於我
            deco: About
          default: *default
    content:
      name: Content/About
  - name: Skill
    path: "/skill"
    layout:
      name: Layout/DefaultLayout
      metadata:
        i18n:
          en: &default
            title: Skill
            deco: 技能樹
          zh:
            title: 技能樹
            deco: Skill
          default: *default
  - name: Experience
    path: "/experience"
    layout:
      name: Layout/DefaultLayout
  - name: Profolio
    path: "/profolio"
    layout:
      name: Layout/DefaultLayout
  - name: Contact
    path: "/contact"
    layout:
      name: Layout/DefaultLayout
