%YAML 1.1
---
themes:
  - &light-theme
    name: light
    description: Light theme
    schema: light
    palettes:
      primary-text-color: $dim
      primary-background-color: $paper
      accent-0: $gray-0
      accent-1: $gray-1
      accent-2: $gray-2
  - &dark-theme
    name: dark
    description: Dark theme
    schema: dark
    palettes:
      primary-text-color: $paper
      primary-background-color: $dim
      accent-0: $gray-2
      accent-1: $gray-1
      accent-2: $gray-0
  - <<: *dark-theme
    name: default
